{% set name = "ply" %}
{% set version = "3.11" %}
{% set python_min = "3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 00c7c1aaa88358b9c765b6d3000c6eec0ba42abca5351b095321aef446081da3

build:
  noarch: python
  number: 4
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - ply.lex
    - ply.yacc

about:
  home: http://www.dabeaz.com/ply/index.html
  license: BSD-3-Clause
  license_family: BSD
  license_file: README.md
  summary: 'Python Lex-Yacc'
  description: |
    PLY is a 100% Python implementation of the common parsing tools lex and
    yacc.
  doc_url: http://www.dabeaz.com/ply/index.html
  dev_url: https://github.com/dabeaz/ply

extra:
  recipe-maintainers:
    - scopatz
    - synapticarbors
